### PR TITLE
Updated react and router

### PR DESCRIPTION
**Pull request by moshie**

### CODE REVIEW

**Comment by remarkablemark** [comment]
@moshie I appreciate the pull request.

Do you mind cherry-picking the changes over to the branch [`upgrade-react-router-4`](https://github.com/remarkablemark/universal-react-tutorial/tree/upgrade-react-router-4), which has the latest code from `master`? This will ensure consistency between my tutorials.

Also, do you mind not bumping `react` and `react-dom` and not committing `yarn.lock` or `package-lock.json`? I'm thinking about doing those tasks separately in one of my later tutorials. Thanks!

**Comment by moshie** [comment]
@remarkablemark No Problem, been enjoying the tutorials!

Yeah sure thing, I'll make those changes on the upgrade-react-router-4 hopefully some time later if not tommorow 👍

**Comment by remarkablemark** [comment]
@moshie Thanks for taking the time to do this.

When I do get to making the video, what's the best way that I can give you credit for your contribution? Would a link to your GitHub work?

**Comment by moshie** [comment]
[Hope this is all ok!](https://github.com/remarkablemark/universal-react-tutorial/pull/5)

A link to my github would be cool thanks 👍

**Pull request closed without merging**
